### ISSUE TITLE
Access session data?

### ISSUE THREAD

**Issue by shayhurley** [egarofalo/Twigniter#1]
I've just started using ci-twig over [codeigniter-ss-twig](https://github.com/kenjis/codeigniter-ss-twig) as it supports twig 2.x - thanks for creating it. 

I'm trying to access session data e.g. flashdata in my twigs but it doesn’t appear to be working. For example:

**Controller**
`$this->session->set_flashdata('message', 'Group added.');`

**Twig**
`{{ session.flashdata.message }}`

The above always returns null :( 

Is there a way to get get access to the session data?

**Comment by egarofalo** [comment]
Hello Shay, you don't have acces to the attribute <code>$this->session</code> of the controller you are in, because it's not a global variable in Twig. Try to add in the constructor function of your controller, the next line: <code>$this->twig->addGlobal('session', $this->session)</code>, and from there you are able to use the session variable in the twig file. Remember, use in twig file <code>session.flashdata('item')</code> to get the flash message.

**Comment by egarofalo** [comment]
Another solution, is to pass the session object to the view: <code>$this->twig->display('view.twig', ['session' => $this->session])</code> and so you can access the session object in the twig file.

**Comment by egarofalo** [comment]
Please star my project!! thanks!!! (=

**Comment by shayhurley** [comment]
Thank you Edgardo - works perfectly - `$this->twig->addGlobal('session', $this->session)`
